version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_iotdevices
    ports:
      - "5432:5432"
    volumes:
      - ../db:/var/lib/postgresql/data